#!/usr/bin/env bash
# comment
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 5430-web-01 54.160.134.25:80 check
        server 5430-web-02 54.221.31.148:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart